app/Entity/Person.php
<?php namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Util\String;

/**
 * @ORM\Entity(repositoryClass="App\Entity\PersonRepository")
 * @ORM\Table(name="person",
 *	indexes={
 *		@ORM\Index(name="name_idx", columns={"name"}),
 *		@ORM\Index(name="last_name_idx", columns={"last_name"}),
 *		@ORM\Index(name="orig_name_idx", columns={"orig_name"}),
 *		@ORM\Index(name="real_name_idx", columns={"real_name"}),
 *		@ORM\Index(name="oreal_name_idx", columns={"oreal_name"}),
 *		@ORM\Index(name="country_idx", columns={"country"}),
 *		@ORM\Index(name="is_author_idx", columns={"is_author"}),
 *		@ORM\Index(name="is_translator_idx", columns={"is_translator"})}
 * )
 * @UniqueEntity(fields="slug", message="This slug is already in use.")
 */
class Person extends Entity {
	/**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="CUSTOM")
	 * @ORM\CustomIdGenerator(class="App\Doctrine\CustomIdGenerator")
	 */
	private $id;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=50, unique=true)
	 */
	private $slug;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100)
	 */
	private $name = '';

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	private $orig_name;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	private $real_name;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	private $oreal_name;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=50, nullable=true)
	 */
	private $last_name;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=10)
	 */
	private $country;

	/** @ORM\Column(type="boolean") */
	private $is_author = true;

	/** @ORM\Column(type="boolean") */
	private $is_translator = false;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=160, nullable=true)
	 */
	private $info;

	/**
	 * @var Person
	 * @ORM\ManyToOne(targetEntity="Person")
	 */
	private $person;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=1, nullable=true)
	 */
	private $type;

//	/**
//	 * @var TextAuthor[]
//	 * @ORM\OneToMany(targetEntity="TextAuthor", mappedBy="person")
//	 */
//	private $textAuthors;
//
//	/**
//	 * @var TextTranslator[]
//	 * @ORM\OneToMany(targetEntity="TextTranslator", mappedBy="person")
//	 */
//	private $textTranslators;

	/**
	 * @var Book[]
	 * @ORM\ManyToMany(targetEntity="Book")
	 */
	private $books;

	/**
	 * @var Series[]
	 * @ORM\ManyToMany(targetEntity="Series", mappedBy="authors")
	 * @ORM\JoinTable(name="series_author")
	 */
	private $series;

	public function getId() { return $this->id; }

	public function setSlug($slug) { $this->slug = String::slugify($slug); }
	public function getSlug() { return $this->slug; }

	public function setName($name) {
		$this->name = $name;
		$this->last_name = self::getLastNameFromName($name);
		if (empty($this->slug)) {
			$this->setSlug($name);
		}
	}
	public function getName() { return $this->name; }

	public function getLastNameFromName($name) {
		preg_match('/([^,]+) ([^,]+)(, .+)?/', $name, $m);
		return isset($m[2]) ? $m[2] : $name;
	}

	public function setOrigName($origName) {
		$this->orig_name = $origName;
		if (empty($this->slug) && preg_match('/[a-z]/', $origName)) {
			$this->setSlug($origName);
		}
	}
	public function getOrigName() { return $this->orig_name; }
	public function orig_name() { return $this->orig_name; }

	public function setRealName($realName) { $this->real_name = $realName; }
	public function getRealName() { return $this->real_name; }

	public function setOrealName($orealName) { $this->oreal_name = $orealName; }
	public function getOrealName() { return $this->oreal_name; }

	public function getLastName() { return $this->last_name; }

	public function setCountry($country) { $this->country = $country; }
	public function getCountry() { return $this->country; }

	public function getIsAuthor() { return $this->is_author; }
	public function getIsTranslator() { return $this->is_translator; }
	public function is_author() { return $this->is_author; }
	public function is_translator() { return $this->is_translator; }
	public function setIsAuthor($isAuthor) { $this->is_author = $isAuthor; }
	public function setIsTranslator($isTranslator) { $this->is_translator = $isTranslator; }

	public function isAuthor($isAuthor = null) {
		if ($isAuthor !== null) {
			$this->is_author = $isAuthor;
		}
		return $this->is_author;
	}

	public function isTranslator($isTranslator = null) {
		if ($isTranslator !== null) {
			$this->is_translator = $isTranslator;
		}
		return $this->is_translator;
	}

	public function getRole() {
		$roles = [];
		if ($this->is_author) $roles[] = 'author';
		if ($this->is_translator) $roles[] = 'translator';

		return implode(',', $roles);
	}

	public function setInfo($info) { $this->info = $info; }
	public function getInfo() { return $this->info; }

	public function setPerson($person) { $this->person = $person; }
	public function getPerson() { return $this->person; }

	public function setType($type) { $this->type = $type; }
	public function getType() { return $this->type; }

	public function getBooks() { return $this->books; }
	public function getSeries() { return $this->series; }

	public function __toString() {
		return $this->name;
	}
}

app/Controller/TranslatorController.php
<?php namespace App\Controller;

use App\Entity\Person;
use Symfony\Component\HttpFoundation\Request;

class TranslatorController extends PersonController {

	public function searchAction(Request $request, $_format) {
		if ($_format == 'suggest') {
			$items = $descs = $urls = [];
			$query = $request->query->get('q');
			$persons = $this->em()->getPersonRepository()->asTranslator()->getByQuery([
				'text'  => $query,
				'by'    => 'name',
				'match' => 'prefix',
				'limit' => 10,
			]);
			foreach ($persons as $person) {
				$items[] = $person['name'];
				$descs[] = '';
				$urls[] = $this->generateUrl('translator_show', ['slug' => $person['slug']], true);
			}

			return $this->asJson([$query, $items, $descs, $urls]);
		}
		return [];
	}

	protected function getShowTemplateParams(Person $person, $format) {
		return $this->getShowTemplateParamsTranslator($person, $format);
	}

	protected function getPersonRepository() {
		return $this->em()->getPersonRepository()->asTranslator();
	}
}

app/Resources/views/Translator/index.html.twig
{% extends 'App::layout.html.twig' %}

{% set title = 'translators'|trans %}
{% block head %}
	{{ parent() }}
	<link rel="search" type="application/opensearchdescription+xml" href="{{ path('translators_search', {'_format': 'osd'}) }}" title="Търсене по преводачи в Моята библиотека" />
	<link rel="search" type="application/opensearchdescription+xml" href="{{ path('persons_search', {'_format': 'osd'}) }}" title="Търсене по личности в Моята библиотека" />
{% endblock %}
{% block content %}
	{% include 'App:Translator:navigation.html.twig' with {'by': '', 'letter': ''} %}
{% endblock %}

app/Resources/views/Translator/index.opds.twig
{% extends 'App::layout.opds.twig' %}
{% import 'App::helper.opds.twig' as helper %}

{% set link_self = helper.url('translators') %}
{% set title = 'Переводчики' %}
{% block content %}
	{{ helper.navi_entry('По малко Имя', updated_at, 'translators_by_alpha_index', {'by': 'first-name'}, 'Списък на преводачите по малко Имя') }}
	{{ helper.navi_entry('По фамилия', updated_at, 'translators_by_alpha_index', {'by': 'last-name'}, 'Списък на преводачите по фамилия') }}
{% endblock %}

app/Resources/views/Translator/list.html.twig
<ul class="superlist">
{% for translator in persons %}
	<li><dl itemscope itemtype="http://schema.org/Person">
		<dt><a href="{{ path('person_show', {'slug': translator.slug}) }}" itemprop="url" data-edit="{{ path('admin_person_edit', {'id': translator.id}) }}">{{ translator.name|name_format(by)|raw }}</a></dt>
		<dd class="country" itemprop="nationality" itemscope itemtype="http://schema.org/Country"><span itemprop="name">{{ ('country.'~translator.country) | trans }}</span></dd>
	</dl></li>
{% else %}
	<li class="no-items">
		{% import 'App::helper.html.twig' as helper %}
		{{ helper.not_found('Няма намерени преводачи.') }}
	</li>
{% endfor %}
</ul>

app/Resources/views/Translator/list_by_alpha.html.twig
{% extends 'App::layout.html.twig' %}

{% set title = ('translators.by.'~by)|trans ~': '~ (letter == '-' ? 'Всички' : letter) %}
{% block content %}

	{% include 'App:Translator:navigation.html.twig' %}
	{% include 'App:Translator:list.html.twig' %}
	{% include 'App::pager.html.twig' %}

{% endblock %}

app/Resources/views/Translator/list_by_alpha.opds.twig
{% extends 'App::layout.opds.twig' %}
{% import 'App::helper.opds.twig' as helper %}

{% set link_self = helper.url('translators_by_alpha', {'by': by, 'letter': letter}) %}
{% set title = ('translators.by.'~by)|trans ~': '~ (letter == '-' ? 'Всички' : letter) %}
{% block content %}

{% macro description(translator, by) %}
	{% if translator.orig_name is not empty %}
		оригинално Имя: {{ translator.orig_name|name_format(by)|striptags }};
	{% endif %}
	държава: {{ ('country.'~translator.country)|trans }}
{% endmacro %}

{% for translator in persons %}
	{{ helper.navi_entry(
		translator.name|name_format(by)|striptags,
		updated_at,
		'translator_show',
		{'slug': translator.slug},
		_self.description(translator, by)) }}
{% endfor %}

	{% include 'App::pager.opds.twig' %}

{% endblock %}

app/Resources/views/Translator/list_by_alpha_index.opds.twig
{% extends 'App::layout.opds.twig' %}
{% import 'App::helper.opds.twig' as helper %}

{% set link_self = helper.url('translators_by_alpha_index', {'by': by}) %}
{% set title = ('translators.by.'~by)|trans %}
{% block content %}
	{{ helper.letter_links('translators_by_alpha', {'by': by}) }}
{% endblock %}

app/Resources/views/Translator/navigation.html.twig
{% import 'App::navi.html.twig' as navi %}
{% if by == 'first-name' or by == '' %}
	<h2>Имя</h2>
	<div class="first-name text-center">
		{{ navi.person_first_letter_links('translators_by_alpha', (by == 'first-name' ? letter : '')) }}
	</div>
{% endif %}
{% if by == 'last-name' or by == '' %}
	<h2>Фамилия</h2>
	<div class="last-name text-center">
		{{ navi.person_last_letter_links('translators_by_alpha', (by == 'last-name' ? letter : '')) }}
	</div>
{% endif %}

app/Resources/views/Translator/search.osd.twig
{% extends 'App::layout.osd.twig' %}
{% set title = 'преводачи' %}

app/Resources/views/Translator/show.html.twig
{% extends 'App::layout.html.twig' %}

{% set title %}
	<a class="selflink" itemprop="name" data-edit="{{ path('admin_person_edit', {id: person.id}) }}">{{ person.name }}</a>
{% endset %}
{% set subtitle = ('person.role.'~person.role)|trans %}
{% block content %}

	<div class="person-{{ person.slug }}">

		<ul id="person-tabs" class="nav nav-tabs">
			{% if texts_as_translator is not empty %}
			<li><a href="#translations" data-toggle="tab"><span class="fa fa-edit"></span> Преводни произведения</a></li>
			{% endif %}
			<li><a href="#article" data-toggle="tab"><span class="fa fa-film"></span> Биография</a></li>
		</ul>

		<div class="tab-content">
			{% if texts_as_translator is not empty %}
			<div class="tab-pane" id="translations">
				{% for series in texts_as_translator %}
					{% include 'App:Translator:texts_list.html.twig' with {'series': series.data, 'texts': series.texts} %}
				{% endfor %}
			</div>
			{% endif %}
			<div class="tab-pane" id="article">
				{% include 'App:Person:info.html.twig' %}
			</div>
		</div>

	</div><!-- end class=person -->
{% endblock %}

{% block inline_js %}
	$("#person-tabs").find("a:first").tab('show');
{% endblock %}

app/Resources/views/Translator/show.opds.twig
{% extends 'App::layout.opds.twig' %}
{% import 'App::helper.opds.twig' as helper %}

{% set link_self = helper.url('translator_show', {'slug': person.slug}) %}
{% set title = person.name ~ ' (преводач)' %}
{% block content %}
	{% for series in texts_as_translator %}
		{% include 'App:Text:list.opds.twig' with {'texts': series.texts} %}
	{% endfor %}
{% endblock %}

app/Resources/views/Translator/texts_list.html.twig
{% import 'App::text.html.twig' as text_lister %}
	<h2>
		{% if series.slug is defined %}
			<a href="{{ path('series_show', {'slug': series.slug}) }}">{{ series.name }}</a>
		{% else %}
			{{ ('text.type.plular.'~series.name) | trans }}
		{% endif %}
	</h2>
	{{ text_lister.text_list_with_author(texts) }}