app/Entity/BaseWork.php
<?php namespace App\Entity;

use App\Service\ContentService;
use App\Util\File;
use App\Util\String;
use Sfblib\SfbConverter;
use Sfblib\SfbToHtmlConverter;

abstract class BaseWork extends Entity {

	const TITLE_NEW_LINE = "<br>\n";

	public static $ratings = [
		6 => 'Шедьовър',
		5 => 'Много добро',
		4 => 'Добро',
		3 => 'Посредствено',
		2 => 'Лошо',
		1 => 'Отвратително',
	];

	protected static $minRating = null;
	protected static $maxRating = null;
	protected static $annotationDir = 'anno';
	protected static $infoDir = 'info';

	protected $hasTitleNote = false;

	public function getDocId() {
		return 'http://chitanka.info';
	}

	public function getType() {
		return 'work';
	}

	abstract public function getId();

	/**
	 * @return string
	 */
	abstract public function getTitle();

	/**
	 * @return string
	 */
	abstract public function getSubtitle();

	/**
	 * @return array
	 */
	abstract public function getLabels();

	/**
	 * Return title and subtitle if any
	 * @param string $format   Output format: %t1 — title, %t2 — subtitle
	 * @return string
	 */
	public function getTitles($format = '%t1 — %t2') {
		if ( ($subtitle = $this->getSubtitle()) ) {
			return strtr($format, [
				'%t1' => $this->getTitle(),
				'%t2' => $subtitle,
			]);
		}

		return $this->getTitle();
	}

	/**
	 * @param int $cnt
	 * @return string
	 */
	public function getTitleAsHtml($cnt = 0) {
		$title = $this->getTitle();

		if ($this->hasTitleNote()) {
			$suffix = SfbConverter::createNoteIdSuffix($cnt, 0);
			$title .= sprintf('<sup id="ref_%s" class="ref"><a href="#note_%s">[0]</a></sup>', $suffix, $suffix);
		}

		return "<h1>$title</h1>";
	}

	/** @return array */
	abstract public function getAuthors();

	/** @return array */
	abstract public function getTranslators();

	/** @return int */
	abstract public function getYear();

	/** @return int */
	abstract public function getTransYear();

	/** @return string */
	abstract public function getPlainSeriesInfo();

	/** @return string */
	abstract public function getPlainTranslationInfo();

	/** @return string */
	abstract public function getAuthorNamesString();

	private $authorIds;
	public function getAuthorIds() {
		if ( ! isset($this->authorIds)) {
			$this->authorIds = [];
			foreach ($this->getAuthors() as $author) {
				$this->authorIds[] = $author->getId();
			}
			sort($this->authorIds);
		}

		return $this->authorIds;
	}

	public function getLang() {
		return '';
	}

	public function getOrigLang() {
		return '';
	}

	/** @return bool */
	public function isTranslation() {
		return $this->getLang() != $this->getOrigLang();
	}

	/** @return string */
	abstract public function getNameForFile();

	/** @return string */
	abstract public function getContentAsSfb();

	/** @return string */
	abstract public function getContentAsFb2();

	public function getContentAsTxt($withBom = true) {
		return ($withBom ? self::getBom() : '') . self::clearSfbMarkers($this->getContentAsSfb());
	}

	private static function clearSfbMarkers($sfbContent) {
		$sfbContent = strtr($sfbContent, [
			">\t" => "\t",
			">>\t" => "\t",
			">>>\t" => "\t",
			">>>>\t" => "\t",
			">>>>>\t" => "\t",
			"|\n" => "\n",
			"A>\n" => "\n", "A$\n" => "\n",
			"I>\n" => "\n", "I$\n" => "\n",
			"D>\n" => "\n", "D$\n" => "\n",
			"E>\n" => "\n", "E$\n" => "\n",
			"L>\n" => "\n", "L$\n" => "\n",
			"S>\n" => "\n", "S$\n" => "\n", "S\t" => "\t",
			"N>\n" => "\n", "N$\n" => "\n", "N\t" => "\t",
			"P>\n" => "\n", "P$\n" => "\n",
			"M$\n" => "\n",
			"C>\n" => "\n", "C$\n" => "\n",
			"F>\n" => "\n", "F$\n" => "\n", "F\t" => "\t",
			"T>\n" => "\n",
			"T$\n" => "\n",
			"#\t" => "\t",
			"|\t" => "\t",
			"!\t" => "\t",
			"@@\t" => "\t",
			"@\t" => "\t",
			'{s}' => '', '{/s}' => '',
			'{e}' => '', '{/e}' => '',
		]);

		$sfbContent = strtr($sfbContent, [
			"\n" => "\r\n",
		]);

		$sfbContent = preg_replace('/M>\t.+/', '', $sfbContent);

		return $sfbContent;
	}

	public function getMaxHeadersDepth() {
		$depth = 1;
		foreach ($this->getHeaders() as $header) {
			if ($depth < $header->getLevel()) {
				$depth = $header->getLevel();
			}
		}

		return $depth;
	}

	public function getHeaders() {
		return [];
	}

	public function getHeadersAsNestedXml($allowEmpty = true) {
		$xml = '';
		$prevlev = 0;
		$lastpos = -1;
		$id = -1;
		foreach ($this->getHeaders() as $i => $header) {
			if ($lastpos != $header->getFpos()) {
				$id++;
			}
			$lastpos = $header->getFpos();

			if ($prevlev < $header->getLevel()) {
				$xml .= "\n<ul>".str_repeat("<li level=$id>\n<ul>", $header->getLevel() - 1 - $prevlev);
			} else if ($prevlev > $header->getLevel()) {
				$xml .= '</li>'.str_repeat("\n</ul>\n</li>", $prevlev - $header->getLevel());
			} else {
				$xml .= '</li>';
			}
			$xml .= "\n<li level=$id>";
			$xml .= htmlspecialchars($header->getName());
			$prevlev = $header->getLevel();
		}
		if ($prevlev) {
			$xml .= '</li>'.str_repeat("\n</ul>\n</li>", $prevlev-1)."\n</ul>";
		} else if ( ! $allowEmpty ) {
			$xml = '<li level=0>Основен текст</li>';
		}

		return $xml;
	}

	private static function loadAnnotation($id) {
		$file = ContentService::getInternalContentFilePath(static::$annotationDir, $id);
		return file_exists($file) ? file_get_contents($file) : null;
	}

	private $annotation;
	public function getAnnotation() {
		return isset($this->annotation) ? $this->annotation : $this->annotation = self::loadAnnotation($this->getId());
	}

	abstract public function setHasAnno($hasAnno);

	public function setAnnotation($annotation) {
		$this->annotation = $annotation;
		$this->setHasAnno($this->annotation != '');
	}

	protected function persistAnnotation() {
		$this->saveContentInFile($this->annotation, static::$annotationDir);
	}

	public function getAnnotationAsSfb() {
		$text = $this->getAnnotation();
		if ($text) {
			$text = SfbConverter::ANNO_S . SfbConverter::EOL
				. rtrim($text) . SfbConverter::EOL
				. SfbConverter::ANNO_E . SfbConverter::EOL
				. SfbConverter::EOL;
		}

		return $text;
	}

	public function getAnnotationAsXhtml($imgDir = null) {
		$text = $this->getAnnotation();
		if ($text) {
			$converter = $this->getSfbConverter($text, $imgDir);
			$converter->convert();
			$text = $converter->getText() . $converter->getNotes(2);
		}

		return $text;
	}

	private static function loadExtraInfo($id) {
		$file = ContentService::getInternalContentFilePath(static::$infoDir, $id);
		return file_exists($file) ? file_get_contents($file) : null;
	}

	private $extraInfo;
	public function getExtraInfo() {
		return isset($this->extraInfo) ? $this->extraInfo : $this->extraInfo = self::loadExtraInfo($this->getId());
	}

	public function setExtraInfo($extraInfo) {
		$this->extraInfo = $extraInfo;
	}

	protected function persistExtraInfo() {
		$this->saveContentInFile($this->extraInfo, static::$infoDir);
	}

	/**
	 * Save a content (annotation, extra info) for the work in a file.
	 * If the content is empty, the corresponding file is deleted.
	 * @param string $content Content to save
	 * @param string $dir     Target directory
	 */
	private function saveContentInFile($content, $dir) {
		$file = ContentService::getInternalContentFilePath($dir, $this->getId());
		$fs = new \Symfony\Component\Filesystem\Filesystem();
		if ($content) {
			$fs->dumpFile($file, String::my_replace($content));
		} else if (file_exists($file) && is_file($file)) {
		        // disable until a nasty deletion bug is resolved
			//unlink($file);
		}
	}

	/**
	 * @param string $imgDir
	 */
	public function getExtraInfoAsXhtml($imgDir = null) {
		$text = $this->getExtraInfo();
		if ($text) {
			$converter = $this->getSfbConverter($text, $imgDir);
			$converter->convert();
			$text = $converter->getText() . $converter->getNotes(2);
		}

		return $text;
	}

	public function getHistoryInfo() {
		return [];
	}

	/**
	 * @param string $imgDir Image directory
	 */
	abstract public function getEpubChunks($imgDir);

	/**
	 * @param string $input  SFB content
	 * @param string $imgDir Image directory
	 */
	protected function getEpubChunksFrom($input, $imgDir) {
		$chapters = [];

		$headers = $this->getHeaders();
		if (count($headers) == 0) {
			$header = new TextHeader;
			$header->setName('Основен текст');
			$header->setFpos(0);
			$header->setLinecnt(1000000);
			$headers = [$header];
		}

		$lastpos = -1;
		foreach ($headers as $header) {
			if ($lastpos != $header->getFpos()) {
				$lastpos = $header->getFpos();
				$converter = $this->getSfbConverter($input, $imgDir);
				$converter->setStartPosition($header->getFpos());
				$converter->setMaxLineCount($header->getLinecnt());
				$converter->convert();
				$text = $converter->getText() . $converter->getNotes(2);
				$chapters[] = ['title' => $header->getName(), 'text'  => $text];
			}
		}

		return $chapters;
	}

	/** @return array */
	abstract public function getImages();

	/** @return array */
	abstract public function getThumbImages();

	/** @return bool */
	abstract public function isGamebook();

	private function getSfbConverter($file, $imgDir) {
		$conv = new SfbToHtmlConverter($file, $imgDir);
		if ($this->isGamebook()) {
			// recognize section links
			$conv->addRegExpPattern('/#(\d+)/', '<a href="#l-$1" class="ep" title="Към част $1">$1</a>');
		}

		return $conv;
	}

	public function hasTitleNote() {
		return $this->hasTitleNote;
	}

	private static function getBom() {
		return File::getBom();
	}

}

app/Entity/TextComment.php
<?php namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
* @ORM\Entity(repositoryClass="App\Entity\TextCommentRepository")
* @ORM\Table(name="text_comment",
*	uniqueConstraints={@ORM\UniqueConstraint(name="user_comment_uniq", columns={"text_id", "rname", "contenthash"})},
*	indexes={
*		@ORM\Index(name="user_idx", columns={"user_id"}),
*		@ORM\Index(name="is_shown_idx", columns={"is_shown"}),
*		@ORM\Index(name="time_idx", columns={"time"})}
* )
*/
class TextComment extends Entity {
	/**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="CUSTOM")
	 * @ORM\CustomIdGenerator(class="App\Doctrine\CustomIdGenerator")
	 */
	private $id;

	/**
	 * @var Text
	 * @ORM\ManyToOne(targetEntity="Text")
	 */
	private $text;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100)
	 */
	private $rname;

	/**
	 * @var int
	 * @ORM\ManyToOne(targetEntity="User")
	 */
	private $user;

	/**
	 * @var string
	 * @ORM\Column(type="text")
	 */
	private $content;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=32)
	 */
	private $contenthash;

	/**
	 * @var \DateTime
	 * @ORM\Column(type="datetime")
	 */
	private $time;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=15)
	 */
	private $ip;

	/**
	 * @var TextComment
	 * @ORM\ManyToOne(targetEntity="TextComment")
	 */
	private $replyto;

	/**
	 * @var bool
	 * @ORM\Column(type="boolean")
	 */
	private $is_shown;

	public function getId() { return $this->id; }

	public function setText($text) { $this->text = $text; }
	public function getText() { return $this->text; }

	public function setRname($rname) { $this->rname = $rname; }
	public function getRname() { return $this->rname; }

	public function setUser($user) { $this->user = $user; }
	public function getUser() { return $this->user; }

	/**
	 * @param string $content
	 */
	public function setContent($content) { $this->content = $content; }
	public function getContent() { return $this->content; }

	/**
	 * @param string $contenthash
	 */
	public function setContenthash($contenthash) { $this->contenthash = $contenthash; }
	public function getContenthash() { return $this->contenthash; }

	/**
	 * @param \DateTime $time
	 */
	public function setTime($time) { $this->time = $time; }
	public function getTime() { return $this->time; }

	public function setIp($ip) { $this->ip = $ip; }
	public function getIp() { return $this->ip; }

	public function setReplyto($replyto) { $this->replyto = $replyto; }
	public function getReplyto() { return $this->replyto; }

	/**
	 * @param bool $isShown
	 */
	public function setIsShown($isShown) { $this->is_shown = $isShown; }
	public function getIsShown() { return $this->is_shown; }

}

app/Form/Type/TextCommentType.php
<?php namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class TextCommentType extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options) {
		$builder
			->add('text_id', 'hidden')
			->add('replyto_id', 'hidden')
			->add('content', 'textarea')
			->add('reader');
	}

	public function getDefaultOptions(array $options) {
		return [
			'data_class' => 'App\Entity\TextComment',
		];
	}

	public function getName() {
		return 'text_comment';
	}
}

app/Controller/Admin/TextCommentController.php
<?php namespace App\Controller\Admin;

class TextCommentController extends CRUDController {
	public function validateCsrfToken($intention) {
		// disable for now
		return true;
	}

}

app/Controller/TextCommentController.php
<?php namespace App\Controller;

class TextCommentController extends Controller {

	public function indexAction($page, $_format) {
		if ($_format == 'rss') {
			$limit = 10;
			return [
				'comments' => $this->em()->getTextCommentRepository()->getLatest($limit),
			];
		}

		$_REQUEST['page'] = $page;

		return $this->legacyPage('Comment');
	}

	public function listForTextAction($id) {
		$this->responseAge = 0;
		$text = $this->em()->getTextRepository()->find($id);

		$_REQUEST['id'] = $id;

		return $this->legacyPage('Comment', [
			'text' => $text,
			'_controller' => 'TextComment:text_comments',
		]);
	}

}

app/Resources/views/TextComment/comment.html.twig
<article class="readercomment" id="e{{ comment.id }}">
	{% if standalone %}
		<h1>
			{% import 'App::text.html.twig' as texttools %}
			За {{ texttools.text_title_with_author(comment.text) }}
		</h1>
	{% endif %}

	<div class="commenttext">
		{{ comment.content|user_markup|raw }}
	</div>

	<footer>
		<ul class="menu" style="float:right">
			<li><a href="{{ path('text_comments', {'id': comment.text.id, 'replyto': comment.id}) }}#e{{ comment.id }}" title="Отговор на коментара" class="js" onclick="return initReply({{ comment.id }})">Отговор</a></li>
			<li><a href="{{ path('text_comments', {'id': comment.text.id}) }}" title="Всички коментари за произведението">Всички коментари</a></li>
		</ul>
		<strong>
			{% if comment.user is not empty %}
				<a href="{{ path('user_show', {'username': comment.user.username}) }}" class="user">{{ comment.user.username }}</a>
			{% else %}
				{{ comment.rname }}
			{% endif %}
		</strong>
		<time datetime="{{ comment.time.format('c') }}" pubdate>({{ comment.time|humandate }})</time>
	</footer>
	<div id="replyto{{ comment.id }}"><!-- TODO remove --></div>
</article>

app/Resources/views/TextComment/comment_form.html.twig
<form action="/lib/comment#e4225" method="post" id="postform">
	<fieldset style="margin-top:2em">
		<div id="commentrules" class="writingrules">
			<p>Уважаеми посетители на сайта, всеки е добре дошъл да изкаже мнението си относно дадено произведение. Имайте предвид, че модераторите ще изтрият коментара или част от него, ако той съдържа обидни и груби нападки към другите, както и ако рекламира собствени възгледи, които не са в контекста на произведението. Ако сте съгласни с това условие, моля, продължете към Отправитьто на коментара си.</p>

			<p>Задължително е попълването на всички полета, както и писането с кирилица. Коментарите с латиница най-вероятно ще бъдат изтрити.</p>

			<p>Спазвайте елементарни правописни правила:</p>
			<ul>
				<li>Започвайте изреченията с главна буква;</li>
				<li>Оставяйте <span title="Синоними: шпация, пауза">интервал</span> след препинателния знак, а не преди него!</li>
			</ul>
			<dl class="instruct"><dt>Разрешени са следните етикети</dt><dd><ul><li>&lt;em&gt;</li><li>&lt;strong&gt;</li></ul></dd>
			</dl>
		</div>

		<legend>Нов коментар</legend>
		<input type="hidden" name="textId" value="3" />
		<input type="hidden" name="chunkId" value="1" />
		<input type="hidden" name="viewType" value="tree" />
		<input type="hidden" name="replyto" value="0" />
		<br>
		<label for="commenttext">Коментар:</label><br>

		<textarea name="commenttext" id="commenttext" cols="77" rows="20" onkeypress="postform_changed = true"></textarea>
		<div><label for="reader">Имя: </label><input type="text" name="reader" id="reader" size="40" maxlength="160" value="" /></div>
		<div><input type="hidden" name="captchaQuestion" value="2" /><input type="hidden" name="captchaQuestionT" value="Колко прави 2 по 4 (словом)?" /><input type="hidden" name="captchaTries" value="0" /><label for="captchaAnswer">Колко прави 2 по 4 (словом)?</label> <input type="text" name="captchaAnswer" id="captchaAnswer" size="30" maxlength="60" /><br></div>

		<div>
			<input type="submit" value="Предварителен преглед" tabindex="0" onclick="if ( ! postform_changed ) { return false; } postform_changed = false; return makePreview(this.form, this.form.commenttext.value, this.form.reader.value)" name="preview" />
			<input type="submit" value="Пращане" tabindex="0" name="send" />
		</div>
	</fieldset>
</form>

app/Resources/views/TextComment/index.rss.twig
{% extends 'App::layout.rss.twig' %}

{% block title 'Нови читателски коментари' %}
{% block content %}
	{% import 'App::person.html.twig' as persontools %}
	{% for comment in comments %}
		<item>
			<title>
				За „{{ comment.text.title }}“
				{% if comment.text.authors|length %}
					от {{ persontools.authors_plain(comment.text.authors) }}
				{% endif %}
			</title>
			<dc:creator>{{ comment.rname }}</dc:creator>
			{% set link = url('text_comments', {'id': comment.text.id}) ~ '#e' ~ comment.id %}
			<link>{{ link }}</link>
			<pubDate>{{ comment.time.format('r') }}</pubDate>
			<guid>{{ link }}</guid>
			<description>{{ comment.content|striptags }}</description>
			<content:encoded><![CDATA[
				{{ comment.content|user_markup|raw }}
			]]></content:encoded>
		</item>
	{% endfor %}
{% endblock %}

app/Resources/views/TextComment/latest_comments.html.twig
{% for comment in comments %}
	{% include 'App:TextComment:comment.html.twig' with {'standalone': true} %}
{% endfor %}

app/Resources/views/TextComment/text_comments.html.twig
{% extends ajax ? 'App::layout.js.twig' : 'App::layout.html.twig' %}

{% set title = 'Читателски коментари' %}
{% set subtitle %}
	{% import 'App::text.html.twig' as texttools %}
	за {{ texttools.text_title_with_author(text) }}
{% endset %}

{% block content %}
	{{ page.getFullContent()|raw }}
	{#
	{% for comment in comments %}
		{% include 'App:TextComment:comment.html.twig' with {'standalone': false} %}
	{% endfor %}
	{% include 'App:TextComment:comment_form.html.twig' %}
	#}
{% endblock %}